# https://taskfile.dev
version: '3'
vars:
  BINFILE: httpfileserver
  IMG: ghcr.io/sgaunet/httpfileserver:latest

tasks:
  default:
    cmds:
      - task list -a
  
  linter:
    cmds:
      - golangci-lint run --timeout 5m

  build:
    cmds:
      - go mod download
      - CGO_ENABLED=0 go build .

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean